### ISSUE TITLE
Support 1.5 IProto protocol 

### ISSUE THREAD

**Issue by kostja** [tarantool/migrate#1]
Add support for 1.5 iporoto protocol please (feature requested by many ppl in mail.ru)

**Comment by Totktonada** [comment]
There are relevant projects:

* https://github.com/moonlibs/connection-legacy: implementation of a client to tarantool 1.5 for tarantool 1.6+. It is possible to implement proxy to 1.5 inside 1.6+ instance.
* https://github.com/shveenkov/tarantool-proxy: implementation of tarantool 1.5 server protocol, which proxies requests to tarantool 1.6+.

I guess the problem is resolved now.
